### ISSUE TITLE
Connection refused errors generate HTTP error code

### ISSUE THREAD

**Issue by sjennison** [SockDrawer/SockSite#21] opened 2015-04-17 17:24 UTC
E_CONN_REFUSED causes a 599 error code in the "history" page, when it really shouldn't generate a code at all...

**Comment by TwelveBaud** [comment] 2015-04-17 17:38
I think this is by design. It's a silly design, but it's _intended_ to artificially raise "`percentage`" (normally 200, corresponding to HTTP's "OK" status) quickly to indicate something's wrong.

**Comment by sjennison** [comment] 2015-04-17 18:27
Ah, I see.

**Comment by AccaliaDeElementia** [comment] 2015-04-17 18:45
it's by design.

i'm mapping connection refused into an unused code in the "Server Error" section of HTTP status codes (as that would be conceptually a server error, outside of the HTTP stack)

I'm seriously considering also mapping the response time to NaN as well as in this case we didn't get a response so there is no response time, so recording ~30-60ms (the time it took to connect and have the server close the connection) is less than useful information and mapping to an absurdly high value is not only polluting the time line but can hide useful information.

I'll need to test to see what happens when i try to graph a NaN value. hopefully plot.ly will handle that in a reasonable manner.

Comments on how this could be handled better are welcome. It may be by design but i'm not married to the design so firmly i can't change it if there's a better model. ;-)

**Comment by TwelveBaud** [comment] 2015-04-17 18:54
Make sure you don't corrupt your aggregation functions if you decide to go that route. PostgreSQL excludes nulls from its aggregates, but JavaScript bubbles it, and I'd really hate to have an entire day's average time unavailable because just one poll was unsuccessful.

**Comment by sjennison** [comment] 2015-04-17 19:02
That makes sense. I wasn't sure if this was something in the bot goofing up or by design. Looks like it's by design :)

**Comment by AccaliaDeElementia** [comment] 2015-04-17 19:03
i'll have to think about NaN vs just leaving the timings in with the code of 599. that's not something i'll do without careful thinking. so it's not going to change soon.

**Comment by RaceProUK** [comment] 2015-04-17 19:04
Assuming plot.ly can handle NaN plots, I see no reason why the JS calcs can't just exclude the NaNs during aggregation. Without looking at the calcs, I can't say for sure, but it's got to be possible.

**Comment by AccaliaDeElementia** [comment] 2015-04-17 19:04
@sjennison it is by design, maybe not the best design, but it is by design. ;-)

it's set here:

https://github.com/AccaliaDeElementia/SockSite/blob/master/check.js#L16-L20

**Comment by TwelveBaud** [comment] 2015-04-17 19:12
The JS calcs absolutely can exclude the NaNs. We just have to remember to do so and remember that it requires [a special incantation](http://ariya.ofilabs.com/2014/05/the-curious-case-of-javascript-nan.html).

**Comment by RaceProUK** [comment] 2015-04-17 19:14
…OK, I read that, and now my brain hates me :laughing:

**Comment by AccaliaDeElementia** [comment] 2015-04-17 19:39
yeah NaN is a paunful thing to deal with.

it's one of the reasons why i'm very hesitant to just slap them in there even if they are conceptually possibly the correct value.

**Comment by AccaliaDeElementia** [comment] 2015-04-19 11:42
Closing Issue: we're switching to an appdex-esque scoring system so the short polls on server unavailable are not an issue and we've sorted out the mystery of the 599 status code.

**Closed as completed by AccaliaDeElementia** 2015-04-19 11:42 UTC

**Comment by riking** [comment] 2015-04-27 02:07
[CLOSED OBSOLETE]
