### ISSUE TITLE
History Tab shows static message

### ISSUE THREAD

**Issue by Deamon-Kid** [SockDrawer/SockSite#44] opened 2015-04-21 14:33 UTC
The message spelling out the status of the server in a funny way does not seem to change with the automatic reloads on the current live site.

Filed Under: [Is there even a tag cloud here?](#tag)

**Comment by TwelveBaud** [comment] 2015-04-21 17:56
Duplicate of issue #27 (which I reopened a few days ago with this specific bug)

**Comment by Onyx47** [comment] 2015-04-21 17:59
Closed as duplicate of #27

**Closed as completed by Onyx47** 2015-04-21 17:59 UTC
Labels: bug, duplicate
